import { Component, Input, } from '@angular/core';
@Component({
  selector: 'app-template1-showcode',
  template: `
  <code>
        <pre>
        &lt;!doctype html&gt;
            &lt;html&gt;
                &lt;head&gt;
                    &lt;meta name="viewport" content="width=device-width" /&gt;
                    &lt;meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /&gt;
                    &lt;title&gt;Mixtape Newsletter - {{getData.headerItems.month}}&lt;/title&gt;
                    &lt;link href="https://fonts.googleapis.com/css?family=Muli&amp;display=swap" rel="stylesheet"&gt;
                &lt;/head&gt;
                &lt;body style="font-size: 16px;font-family: 'Muli', sans-serif;background-color: #ffffff;margin:0;padding:0;line-height: 1.5;"&gt;
                    &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                        &lt;tr&gt;
                            &lt;td align="center" style="font-size: 16px;font-family: 'Muli', sans-serif;"&gt;
                                &lt;table width="600" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                    &lt;tbody&gt;
                                        &lt;tr&gt;
                                            &lt;td&gt;
                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation" style="width:100% !important;"&gt;
                                                    &lt;tr height="20"&gt;&lt;td colspan="2" valign="top"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                    &lt;tr&gt;
                                                        &lt;td valign="middle"&gt;&lt;img src="{{getData.headerItems.logo}}" alt="Mixtape - The design newsletter" width="180" /&gt;&lt;/td&gt;
                                                        &lt;td align="right" valign="middle"&gt;&lt;p style="margin: 0;font-size: 80%;text-align: right;font-family: 'Muli', sans-serif;"&gt;{{getData.headerItems.month}}&lt;/p&gt;&lt;/td&gt;
                                                    &lt;/tr&gt;
                                                    &lt;tr height="15"&gt;&lt;td colspan="2" valign="top" style="border-bottom: 1px solid #000;"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                &lt;/table&gt;
                                            &lt;/td&gt;
                                        &lt;/tr&gt;
                                    &lt;/tbody&gt;
                                    &lt;tbody&gt;
                                        &lt;tr&gt;
                                            &lt;td&gt;
                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation" id="topPicks"&gt;
                                                    &lt;tbody&gt;
                                                        &lt;tr height="30"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                        &lt;tr&gt;
                                                            &lt;td width="10"&gt;&lt;/td&gt;
                                                            &lt;td&gt;
                                                                &lt;p style="margin:0;font-family: 'Muli', sans-serif;"&gt;{{getData.topPicks.quote}}&lt;/p&gt;
                                                                &lt;span style="color: #BCBDC2;font-size: 75%;font-family: 'Muli', sans-serif;"&gt;- Found on the internet&lt;/span&gt;
                                                            &lt;/td&gt;
                                                            &lt;td width="10"&gt;&lt;/td&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="10"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                        &lt;tr&gt;
                                                            &lt;td width="10"&gt;&lt;/td&gt;
                                                            &lt;td&gt;
                                                                &lt;img src="{{getData.topPicks.illustration}}" alt="Illustration of the month" width="100%" style="vertical-align: top;" /&gt;
                                                                &lt;p style="color: #BCBDC2;font-size: 75%;margin:5px 0 0 0;font-family: 'Muli', sans-serif;"&gt;Artwork by &lt;a href="{{getData.topPicks.artistlink}}" target="_blank" style="color: #BCBDC2;font-size: 12px;margin:0"&gt;{{getData.topPicks.artworkby}}&lt;/a&gt;&lt;/p&gt;
                                                            &lt;/td&gt;
                                                            &lt;td width="10"&gt;&lt;/td&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="25"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                        &lt;tr&gt;
                                                            &lt;td width="10"&gt;&lt;/td&gt;
                                                            &lt;td id="introductionContent"&gt;
                                                                &lt;h1 style="margin: 0;mso-line-height-rule:exactly;font-size: 150%;font-family: Georgia, 'Times New Roman', sans-serif;font-weight: normal;"&gt;{{getData.introduction.title}}&lt;/h1&gt;
                                                                &lt;p style="margin:10px 0 0 0;font-family: 'Muli', sans-serif;"&gt;{{getData.introduction.description}}&lt;/p&gt;
                                                            &lt;/td&gt;
                                                            &lt;td width="10"&gt;&lt;/td&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="20"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                &lt;/table&gt;
                                            &lt;/td&gt;
                                        &lt;/tr&gt;
                                    &lt;/tbody&gt;
                                    &lt;tbody&gt;
                                        &lt;tr&gt;
                                            &lt;td&gt;
                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation" id="sideA"&gt;
                                                    &lt;thead&gt;
                                                        &lt;tr height="25"&gt;&lt;th colspan="3"&gt;&lt;/th&gt;&lt;/tr&gt;
                                                        &lt;tr&gt;
                                                            &lt;th width="10"&gt;&lt;/th&gt;
                                                            &lt;th align="left"&gt;
                                                                &lt;h2 style="margin: 0;mso-line-height-rule:exactly;font-size: 150%;font-family: Georgia, 'Times New Roman', sans-serif;font-weight: normal;"&gt;Side A&lt;/h2&gt;
                                                            &lt;/th&gt;
                                                            &lt;th width="10"&gt;&lt;/th&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="10"&gt;&lt;th colspan="3"&gt;&lt;/th&gt;&lt;/tr&gt;
                                                    &lt;/thead&gt;    
                                                    &lt;tbody&gt;
                                                        &lt;tr&gt;
                                                            &lt;td colspan="3"&gt;
                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#EFF3F4" role="Presentation"&gt;
                                                                    &lt;tbody&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                        &lt;tr&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                            &lt;td&gt;
                                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                                                                    &lt;tbody&gt;
                                                                                        &lt;tr&gt;
                                                                                            &lt;td width="40%" valign="top"&gt;
                                                                                                &lt;a href="{{getData.sideA[0].link}}" target="_blank"&gt;
                                                                                                    &lt;img src="{{getData.sideA[0].imageURL}}" alt="{{getData.sideA[0].title}}" width="100%" style="vertical-align: top;" /&gt;
                                                                                                &lt;/a&gt;
                                                                                            &lt;/td&gt;
                                                                                            &lt;td width="15" valign="top"&gt;&lt;/td&gt;
                                                                                            &lt;td  valign="top"&gt;
                                                                                                &lt;span style="font-size: 80%;font-family: 'Muli', sans-serif;color:#666;text-transform: uppercase;"&gt;{{getData.sideA[0].tag}}&lt;/span&gt;
                                                                                                &lt;h3 style="margin: 0;mso-line-height-rule:exactly;font-size: 110%;font-weight: bold;line-height: 1.2;font-family: 'Muli', sans-serif;"&gt;{{getData.sideA[0].title}}&lt;/h3&gt;
                                                                                                &lt;p style="margin:10px 0 10px 0;font-family: 'Muli', sans-serif;line-height: 1.3;"&gt;{{getData.sideA[0].description}}&lt;/p&gt;
                                                                                                &lt;a href="{{getData.sideA[0].link}}" target="_blank" style="color:#4096c8;text-decoration: none;font-family: 'Muli', sans-serif;"&gt;Read Through&lt;/a&gt;
                                                                                            &lt;/td&gt;
                                                                                        &lt;/tr&gt;
                                                                                    &lt;/tbody&gt;
                                                                                &lt;/table&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                        &lt;/tr&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                    &lt;/tbody&gt;
                                                                &lt;/table&gt;
                                                            &lt;/td&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="30"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                    &lt;tbody&gt;
                                                        &lt;tr&gt;
                                                            &lt;td colspan="3"&gt;
                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#EFF3F4" role="Presentation"&gt;
                                                                    &lt;tbody&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                        &lt;tr&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                            &lt;td&gt;
                                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                                                                    &lt;tbody&gt;
                                                                                        &lt;tr&gt;
                                                                                            &lt;td width="40%" valign="top"&gt;
                                                                                                &lt;a href="{{getData.sideA[1].link}}" target="_blank"&gt;
                                                                                                    &lt;img src="{{getData.sideA[1].imageURL}}" alt="{{getData.sideA[1].title}}" width="100%" style="vertical-align: top;" /&gt;
                                                                                                &lt;/a&gt;
                                                                                            &lt;/td&gt;
                                                                                            &lt;td width="15" valign="top"&gt;&lt;/td&gt;
                                                                                            &lt;td  valign="top"&gt;
                                                                                                &lt;span style="font-size: 80%;font-family: 'Muli', sans-serif;color:#666;text-transform: uppercase;"&gt;{{getData.sideA[1].tag}}&lt;/span&gt;
                                                                                                &lt;h3 style="margin: 0;mso-line-height-rule:exactly;font-size: 110%;font-weight: bold;line-height: 1.2;font-family: 'Muli', sans-serif;"&gt;{{getData.sideA[1].title}}&lt;/h3&gt;
                                                                                                &lt;p style="margin:10px 0 10px 0;font-family: 'Muli', sans-serif;line-height: 1.3;"&gt;{{getData.sideA[1].description}}&lt;/p&gt;
                                                                                                &lt;a href="{{getData.sideA[1].link}}" target="_blank" style="color:#4096c8;text-decoration: none;font-family: 'Muli', sans-serif;"&gt;Read Through&lt;/a&gt;
                                                                                            &lt;/td&gt;
                                                                                        &lt;/tr&gt;
                                                                                    &lt;/tbody&gt;
                                                                                &lt;/table&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                        &lt;/tr&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                    &lt;/tbody&gt;
                                                                &lt;/table&gt;
                                                            &lt;/td&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="30"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                    &lt;tbody&gt;
                                                        &lt;tr&gt;
                                                            &lt;td colspan="3"&gt;
                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#EFF3F4" role="Presentation"&gt;
                                                                    &lt;tbody&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                        &lt;tr&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                            &lt;td&gt;
                                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                                                                    &lt;tbody&gt;
                                                                                        &lt;tr&gt;
                                                                                            &lt;td width="40%" valign="top"&gt;
                                                                                                &lt;a href="{{getData.sideA[2].link}}" target="_blank"&gt;
                                                                                                    &lt;img src="{{getData.sideA[2].imageURL}}" alt="{{getData.sideA[2].title}}" width="100%" style="vertical-align: top;" /&gt;
                                                                                                &lt;/a&gt;
                                                                                            &lt;/td&gt;
                                                                                            &lt;td width="15" valign="top"&gt;&lt;/td&gt;
                                                                                            &lt;td  valign="top"&gt;
                                                                                                &lt;span style="font-size: 80%;font-family: 'Muli', sans-serif;color:#666;text-transform: uppercase;"&gt;{{getData.sideA[2].tag}}&lt;/span&gt;
                                                                                                &lt;h3 style="margin: 0;mso-line-height-rule:exactly;font-size: 110%;font-weight: bold;line-height: 1.2;font-family: 'Muli', sans-serif;"&gt;{{getData.sideA[2].title}}&lt;/h3&gt;
                                                                                                &lt;p style="margin:10px 0 10px 0;font-family: 'Muli', sans-serif;line-height: 1.3;"&gt;{{getData.sideA[2].description}}&lt;/p&gt;
                                                                                                &lt;a href="{{getData.sideA[2].link}}" target="_blank" style="color:#4096c8;text-decoration: none;font-family: 'Muli', sans-serif;"&gt;Read Through&lt;/a&gt;
                                                                                            &lt;/td&gt;
                                                                                        &lt;/tr&gt;
                                                                                    &lt;/tbody&gt;
                                                                                &lt;/table&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                        &lt;/tr&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                    &lt;/tbody&gt;
                                                                &lt;/table&gt;
                                                            &lt;/td&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="30"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                &lt;/table&gt;
                                            &lt;/td&gt;
                                        &lt;/tr&gt;
                                    &lt;/tbody&gt;
                                    &lt;tbody&gt;
                                        &lt;tr&gt;
                                            &lt;td&gt;
                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#FDDCBD" role="Presentation" id="nowRolling"&gt;
                                                    &lt;thead&gt;
                                                        &lt;tr height="20"&gt;&lt;th colspan="3"&gt;&lt;/th&gt;&lt;/tr&gt;
                                                        &lt;tr&gt;
                                                            &lt;th width="15"&gt;&lt;/th&gt;
                                                            &lt;th align="left"&gt;
                                                                &lt;h2 style="margin: 0;mso-line-height-rule:exactly;font-size: 150%;font-family: Georgia, 'Times New Roman', sans-serif;font-weight: normal;"&gt;Now Rolling&lt;/h2&gt;
                                                            &lt;/th&gt;
                                                            &lt;th width="15"&gt;&lt;/th&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="15"&gt;&lt;th colspan="3"&gt;&lt;/th&gt;&lt;/tr&gt;
                                                    &lt;/thead&gt;   
                                                    &lt;tbody&gt;
                                                        &lt;tr&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                            &lt;td&gt;
                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                                                    &lt;tbody&gt;
                                                                        &lt;tr&gt;
                                                                            &lt;td align="center" valign="top" style="line-height: 1.3;color: #4096c8;font-family: 'Muli', sans-serif;"&gt;
                                                                                &lt;div style="max-width: 180px;"&gt;
                                                                                    &lt;a href="{{getData.nowRolling[0].link}}" target="_blank" style="text-decoration: none;color: #4096c8;font-family: 'Muli', sans-serif;"&gt;
                                                                                        &lt;img src="{{getData.nowRolling[0].image}}" alt="{{nowRolling[0].title}}" style="width:100%;max-width:180px;" /&gt;
                                                                                        &lt;span&gt;{{getData.nowRolling[0].title}}&lt;/span&gt;
                                                                                    &lt;/a&gt;
                                                                                &lt;/div&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                            &lt;td align="center" valign="top" style="line-height: 1.3;color: #4096c8;font-family: 'Muli', sans-serif;"&gt;
                                                                                &lt;div style="max-width: 180px;"&gt;
                                                                                    &lt;a href="{{getData.nowRolling[1].link}}" target="_blank" style="text-decoration: none;color: #4096c8;font-family: 'Muli', sans-serif;"&gt;
                                                                                        &lt;img src="{{getData.nowRolling[1].image}}" alt="{{nowRolling[1].title}}" style="width:100%;max-width:180px;" /&gt;
                                                                                        &lt;span&gt;{{getData.nowRolling[1].title}}&lt;/span&gt;
                                                                                    &lt;/a&gt;
                                                                                &lt;/div&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                                            &lt;td align="center" valign="top" style="line-height: 1.3;color: #4096c8;font-family: 'Muli', sans-serif;"&gt;
                                                                                &lt;div style="max-width: 180px;"&gt;
                                                                                    &lt;a href="{{getData.nowRolling[2].link}}" target="_blank" style="text-decoration: none;color: #4096c8;font-family: 'Muli', sans-serif;"&gt;
                                                                                        &lt;img src="{{getData.nowRolling[2].image}}" alt="{{nowRolling[2].title}}" style="width:100%;max-width:180px;" /&gt;
                                                                                        &lt;span&gt;{{getData.nowRolling[2].title}}&lt;/span&gt;
                                                                                    &lt;/a&gt;
                                                                                &lt;/div&gt;
                                                                            &lt;/td&gt;
                                                                        &lt;/tr&gt;
                                                                    &lt;/tbody&gt;
                                                                &lt;/table&gt;
                                                            &lt;/td&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="15"&gt;&lt;th colspan="3"&gt;&lt;/th&gt;&lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                &lt;/table&gt;
                                            &lt;/td&gt;
                                        &lt;/tr&gt;
                                    &lt;/tbody&gt;
                                    &lt;tbody&gt;
                                        &lt;tr height="30"&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;
                                        &lt;tr&gt;
                                            &lt;td&gt;
                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#E0E5FF" role="Presentation" id="cassetteLibrary"&gt;
                                                    &lt;thead&gt;
                                                        &lt;tr height="20"&gt;&lt;th colspan="3"&gt;&lt;/th&gt;&lt;/tr&gt;
                                                        &lt;tr&gt;
                                                            &lt;th width="15"&gt;&lt;/th&gt;
                                                            &lt;th align="left"&gt;
                                                                &lt;h2 style="margin: 0;mso-line-height-rule:exactly;font-size: 150%;font-family: Georgia, 'Times New Roman', sans-serif;font-weight: normal;"&gt;Cassette Library&lt;/h2&gt;
                                                            &lt;/th&gt;
                                                            &lt;th width="15"&gt;&lt;/th&gt;
                                                        &lt;/tr&gt;
                                                        &lt;tr height="15"&gt;&lt;th colspan="3"&gt;&lt;/th&gt;&lt;/tr&gt;
                                                    &lt;/thead&gt;   
                                                    &lt;tbody&gt;
                                                        &lt;tr&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                            &lt;td&gt;
                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                                                    &lt;tbody&gt;
                                                                        &lt;tr&gt;
                                                                            &lt;td width="40%" valign="top"&gt;
                                                                                &lt;a href="{{getData.cassetteLibrary[0].link}}" target="_blank"&gt;
                                                                                    &lt;img src="{{getData.cassetteLibrary[0].image}}" alt="{{getData.cassetteLibrary[0].title}}" width="100%" style="vertical-align: top;" /&gt;
                                                                                &lt;/a&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15" valign="top"&gt;&lt;/td&gt;
                                                                            &lt;td  valign="top"&gt;
                                                                                &lt;h3 style="margin: 0;mso-line-height-rule:exactly;font-size: 110%;font-weight: bold;line-height: 1.2;font-family: 'Muli', sans-serif;"&gt;{{getData.cassetteLibrary[0].title}}&lt;/h3&gt;
                                                                                &lt;p style="margin:10px 0 10px 0;font-family: 'Muli', sans-serif;line-height: 1.3;"&gt;{{getData.cassetteLibrary[0].description}}&lt;/p&gt;
                                                                                &lt;a href="{{getData.cassetteLibrary[0].link}}" target="_blank" style="color:#4096c8;text-decoration: none;font-family: 'Muli', sans-serif;"&gt;Read Through&lt;/a&gt;
                                                                            &lt;/td&gt;
                                                                        &lt;/tr&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                    &lt;/tbody&gt;
                                                                &lt;/table&gt;
                                                            &lt;/td&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                        &lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                    &lt;tbody&gt;
                                                        &lt;tr&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                            &lt;td&gt;
                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                                                    &lt;tbody&gt;
                                                                        &lt;tr&gt;
                                                                            &lt;td width="40%" valign="top"&gt;
                                                                                &lt;a href="{{getData.cassetteLibrary[1].link}}" target="_blank"&gt;
                                                                                    &lt;img src="{{getData.cassetteLibrary[1].image}}" alt="{{getData.cassetteLibrary[1].title}}" width="100%" style="vertical-align: top;" /&gt;
                                                                                &lt;/a&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15" valign="top"&gt;&lt;/td&gt;
                                                                            &lt;td  valign="top"&gt;
                                                                                &lt;h3 style="margin: 0;mso-line-height-rule:exactly;font-size: 110%;font-weight: bold;line-height: 1.2;font-family: 'Muli', sans-serif;"&gt;{{getData.cassetteLibrary[1].title}}&lt;/h3&gt;
                                                                                &lt;p style="margin:10px 0 10px 0;font-family: 'Muli', sans-serif;line-height: 1.3;"&gt;{{getData.cassetteLibrary[1].description}}&lt;/p&gt;
                                                                                &lt;a href="{{getData.cassetteLibrary[1].link}}" target="_blank" style="color:#4096c8;text-decoration: none;font-family: 'Muli', sans-serif;"&gt;Read Through&lt;/a&gt;
                                                                            &lt;/td&gt;
                                                                        &lt;/tr&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                    &lt;/tbody&gt;
                                                                &lt;/table&gt;
                                                            &lt;/td&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                        &lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                    &lt;tbody&gt;
                                                        &lt;tr&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                            &lt;td&gt;
                                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation"&gt;
                                                                    &lt;tbody&gt;
                                                                        &lt;tr&gt;
                                                                            &lt;td width="40%" valign="top"&gt;
                                                                                &lt;a href="{{getData.cassetteLibrary[2].link}}" target="_blank"&gt;
                                                                                    &lt;img src="{{getData.cassetteLibrary[2].image}}" alt="{{getData.cassetteLibrary[2].title}}" width="100%" style="vertical-align: top;" /&gt;
                                                                                &lt;/a&gt;
                                                                            &lt;/td&gt;
                                                                            &lt;td width="15" valign="top"&gt;&lt;/td&gt;
                                                                            &lt;td  valign="top"&gt;
                                                                                &lt;h3 style="margin: 0;mso-line-height-rule:exactly;font-size: 110%;font-weight: bold;line-height: 1.2;font-family: 'Muli', sans-serif;"&gt;{{getData.cassetteLibrary[2].title}}&lt;/h3&gt;
                                                                                &lt;p style="margin:10px 0 10px 0;font-family: 'Muli', sans-serif;line-height: 1.3;"&gt;{{getData.cassetteLibrary[2].description}}&lt;/p&gt;
                                                                                &lt;a href="{{getData.cassetteLibrary[2].link}}" target="_blank" style="color:#4096c8;text-decoration: none;font-family: 'Muli', sans-serif;"&gt;Read Through&lt;/a&gt;
                                                                            &lt;/td&gt;
                                                                        &lt;/tr&gt;
                                                                        &lt;tr height="15"&gt;&lt;td colspan="3"&gt;&lt;/td&gt;&lt;/tr&gt;
                                                                    &lt;/tbody&gt;
                                                                &lt;/table&gt;
                                                            &lt;/td&gt;
                                                            &lt;td width="15"&gt;&lt;/td&gt;
                                                        &lt;/tr&gt;
                                                    &lt;/tbody&gt;
                                                &lt;/table&gt;
                                            &lt;/td&gt;
                                        &lt;/tr&gt;
                                    &lt;/tbody&gt;
                                    &lt;tbody&gt;
                                        &lt;tr height="30"&gt;
                                            &lt;td bgcolor="#ffffff"&gt;
                                                &lt;table width="100%" cellpadding="0" cellspacing="0" border="0" role="Presentation" style="width:100% !important;"&gt;
                                                    &lt;tr&gt;
                                                        &lt;td width="10"&gt;&lt;/td&gt;
                                                        &lt;td valign="middle"&gt;&lt;p style="margin: 0;font-size: 60%;font-family: 'Muli', sans-serif;"&gt;Copyright 1997-2020 Pramati Technologies. All Rights Reserved.&lt;/p&gt;&lt;/td&gt;
                                                        &lt;td valign="middle" align="right"&gt;
                                                            &lt;a href="https://www.pramati.com/" target="_blank"&gt;&lt;img src="http://bit.ly/2XO3h97" alt="Pramati Technologies" width="50" /&gt; &lt;/a&gt;
                                                        &lt;/td&gt;
                                                        &lt;td width="10"&gt;&lt;/td&gt;
                                                    &lt;/tr&gt;
                                                &lt;/table&gt;
                                            &lt;/td&gt;
                                        &lt;/tr&gt;
                                    &lt;/tbody&gt;
                                &lt;/table&gt;
                            &lt;/td&gt;
                        &lt;/tr&gt;
                    &lt;/table&gt;
                &lt;/body&gt;
            &lt;/html&gt;
        </pre>
    </code>

`,
  //encapsulation: ViewEncapsulation.None,
})
export class Template1ComponentShowcode{
  @Input() headerItems: any;
  @Input() introduction: any;
  @Input() topPicks: any;
  @Input() sideA: any;
  @Input() nowRolling: any;
  @Input() cassetteLibrary: any;
  @Input() getData: any;

 

  //constructor(private _mixtapeContent: GlobalsService) { }
  ngOnInit() {
    // this.headerItems = this._mixtapeContent.headerItems;
    // this.introduction = this._mixtapeContent.introduction;
    // this.topPicks = this._mixtapeContent.topPicks;
    // this.sideA = this._mixtapeContent.sideA;
    // this.nowRolling = this._mixtapeContent.nowRolling;
    // this.cassetteLibrary = this._mixtapeContent.cassetteLibrary;
    //console.log(this.getData);
  }
  

}
